services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: project_tracker_frontend
    ports:
      - "3007:3000"
    environment:
      - NEXT_PUBLIC_API_URL=/api/v1
      - NEXT_PUBLIC_APP_NAME=ProjectTracker
      - NEXT_PUBLIC_APP_URL=http://localhost:3000
    networks:
      - dac_network

networks:
  dac_network:
    external: true
